### ISSUE TITLE
Remind people to update their NPM prefix if installing PureScript via NPM

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-book#130]
The installation guide shows how to use `npm` to install both the PureScript compiler and Spago. However, it never mentions anything about changing the prefix of npm after installing node. Without that, people may install things via `sudo` when that isn't necessary.

See [my summary of Justin Woo's post](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/00-Getting-Started/02-Install-Guide.md#manual-install) on this issue.

**Comment by hdgarrood** [comment]
I think it's also worth considering having the guide recommend installing everything locally, which sidesteps the issue

**Comment by milesfrain** [comment]
Wouldn't local install require all commands to prefixed with `npx`? I'd rather allow commands like `spago build` to be pasted to console directly, instead of needing to update all of those to `npx spago build`.

This note about modifying the prefix for installing global packages is [already part of the guide in the docs repo](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md#installing-the-compiler), and so consolidating the guides (#93) should address this issue.

The note could probably be improved though, since [some users miss it](https://functionalprogramming.slack.com/archives/C717K38CE/p1587843094471900), and don't realize that it's the solution to their `EACCES` errors (scroll down for their screenshot with `EACCES` error).

**Comment by hdgarrood** [comment]
Local install means that you have to either prefix commands with `npx` or put them in npm scripts. I think npm scripts are a good option, though. My impression is that the vast majority of the JS ecosystem encourages local installation of any development tools like bundlers or compilers these days, because global installs are a pain when moving across projects with differing versions. I agree on consolidating the guides by the way, I just haven't gotten around to responding on that yet.

**Comment by milesfrain** [comment]
Local installation was my original recommendation for the templates ([guide](https://github.com/purescript-templates/docs/blob/master/versioned-toolchain.md)), but I figured global installation was a better default recommendation for the following reasons:
* Project setup time. Takes me about 20 seconds to run `npm install`
* Disk usage. Adds an extra 200MB per project.

It seems like there should be some way to cache all of these dependencies in a global location and point to them from the local directory (assuming they're identical between projects). Maybe I have something misconfigured where the cache is ignored.

Demonstration of issues with install time and disk usage:
```
> git clone --depth 1 https://github.com/purescript-templates/halogen.git local
> cd local
> time npm install
npm install  18.88s user 2.42s system 104% cpu 20.355 total
> du -hs .          
202M    .
```

**Comment by hdgarrood** [comment]
Both good points. The purescript npm install does cache binaries in a global location, but it also copies the binary into each `node_modules` directory. (The `purs` binary is about 50MB.) I'm sure we can do something about that. Spago's install script downloads the `spago` binary fresh each time, which takes longer. We could potentially take the purescript npm installer and pull out the `purs`-specific bits so that it can be used to download and install spago too, and that way spago could benefit from the code that caches binaries to avoid having to redownload them, and can fall back to installing from source, etc, if @f-f likes the sound of that.

**Comment by f-f** [comment]
@hdgarrood yeah this sounds amazing to me :slightly_smiling_face:

**Comment by hdgarrood** [comment]
I just want to make sure you're aware of what you may be getting yourself in for; have you seen the source code? It's at https://github.com/purescript/npm-installer/. It's all JS and it's ... quite involved. It took me a while to get my head around it when we first moved it into the `purescript` org.

**Comment by f-f** [comment]
I'm not getting into anything, the Spago npm installer is that minimal exactly because I despise writing JS (I guess that's also why I do PureScript :smile:), so I think I won't do much myself about this.
If anyone wants to look at it PRs are more than welcome though :slightly_smiling_face:

**Comment by hdgarrood** [comment]
Haha, fair enough. I more meant from the perspective of the liability introduced by depending on code that’s harder to debug in case it did go wrong, rather than actually actively contributing to it. The npm package seems to work well enough these days though, I think all of the open bugs on it are caused by the binaries not being able to run on the user’s machine at all.

**Comment by f-f** [comment]
Yeah I think I'm ok with depending on that code now that it's in good hands - as you said it's very stable these days :slightly_smiling_face: 
And maybe some day some hero will [port it to PureScript](https://github.com/purescript/npm-installer/issues/5)..

**Comment by JordanMartinez** [comment]
So... getting back on track of the original issue :smile:, what actions should we take to address the immediate issue? The fact is we are instructing users to globally install PureScript but have no mention of the NPM prefix. 
Are we in agreement that, for the time being, we warn people about that?

**Comment by milesfrain** [comment]
Filed #131 to immediately address this concern.
The longer term goal is to merge the getting started guides.

**Comment by JordanMartinez** [comment]
Closed by #131

**Comment by milesfrain** [comment]
Revisiting the local installation suggestion from earlier:

`pnpn` (as demonstrated in @Mateiadrielrafael's [repo](https://github.com/Mateiadrielrafael/purescript-halogen-template)) is about 2x faster than `npm` and supposedly doesn't add any disk usage. Disk usage is still listed, but this is supposedly an [effect of hard links](https://pnpm.js.org/en/faq#why-does-my-node_modules-folder-use-disk-space-if-packages-are-stored-in-a-global-store). Wondering if `npm` is also using hard links.

~10 seconds still seems too long though.

```
> git clone --depth 1 https://github.com/purescript-templates/halogen.git local
> cd local
> time pnpm install
pnpm install  11.45s user 2.54s system 105% cpu 13.207 total
> du -hs .          
204M    .
```

**Comment by hdgarrood** [comment]
I wouldn't want to recommend and npm registry clients other than `npm` itself. I expect the majority of the time is spent in install scripts for `purs` and `spago` anyway, so switching to a different client won't affect that.

**Comment by Mateiadrielrafael** [comment]
Even tho I'm a giant pnpm fan I gotta agree with @hdgarrood - beginners might be confused by requiring a different npm client

A small footnote mentioning it might be fine tho

**Comment by f-f** [comment]
Spago [apparently has trouble with `pnpm`](https://github.com/purescript/spago/issues/433), so I'm with @hdgarrood here in not recommending anything else than the official client.
