### ISSUE TITLE
`Either e` vs `Either`

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#160]
I'm second-guessing whether the `e` removed in #159 is really a typo.

The are lots of other `Either e` and `ExceptT e` [appearances in the book](https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter11.md#the-exceptt-monad-transformer). But then there are many other appearances without the `e`.

Not sure if there's a reason behind the various forms.

If it's just a matter of preference, I'd prefer the `e`-free form.

**Comment by hdgarrood** [comment]
It's neither a typo nor a matter of preference. The Functor class requires a parameter of kind Type -> Type. However, the Either type constructor has kind Type -> Type -> Type (it takes two parameters of kind Type, and gives you back something of kind Type. It's more accurate to talk about the `Either e` monad, because you have to give Either one type parameter to get something of kind Type -> Type, which can be given a Monad instance. When you actually write the instance, you have to write `instance monadEither :: Monad (Either e) where [...]` for this reason.

**Comment by milesfrain** [comment]
Would it be more correct to write `ExceptT e` as `ExeptT e m` then?
Or what about listing all the type variables?
```
Either e a
ExceptT e m a
```
I see various options used here https://pursuit.purescript.org/packages/purescript-transformers/4.2.0/docs/Control.Monad.Except.Trans#t:ExceptT

**Comment by milesfrain** [comment]
Okay, I see that in this context
> The interested reader can check that `ap` agrees with `apply` for the monads we have already encountered: `Array`, `Maybe` and `Either e`.
That `Either e` is a monad, but `Either` is not a monad, since it's missing some information.
Likewise `ExtceptT e m` is a monad, as can be seen here:
```
(Monad m) => Apply (ExceptT e m)
```

**Comment by hdgarrood** [comment]
> Would it be more correct to write ExceptT e as ExeptT e m then?

Not necessarily. It depends on context. When you're talking about a monad transformer, such as here https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter11.md#the-exceptt-monad-transformer:

> The transformers package also defines the `ExceptT e` monad transformer, which is the transformer corresponding to the `Either e` monad.

then writing `ExceptT e` is the most appropriate way of doing it, because a monad transformer is a type constructor `T` of kind `(Type -> Type) -> Type -> Type` with the property that `T m` is a monad as long as `m` is.

I wouldn't recommend listing all of the type variables. A big part of what makes monads monads is parametricity; they can't change their behaviour based on the type parameter. So `>>=` for `Either e` always works the same way, regardless of whether I end up using `>>=` on an `Either e Int` or an `Either e String` or whatever. (Note, in the case of PureScript we don't need to specify that monads need to behave this way because the type system guarantees it for us.)

**Comment by hdgarrood** [comment]
Right, whenever you're looking at a list of instances, the number of parameters given is almost never arbitrary, there's almost always only one way of writing a given instance, which is based on the kinds of the class's parameters.
