### ISSUE TITLE
Ch4 function definition and pattern matching

### ISSUE THREAD

**Issue by Ding-Fan** [purescript-contrib/purescript-book#215]
People without Haskell experience would be confused by these code examples:

> ...
> Here is the usual factorial function example:
>
> ```purescript
> fact :: Int -> Int
> fact 0 = 1
> fact n = n * fact (n - 1)
> ```
> ...
> Here is another common example, which computes the Fibonnacci function:
> 
> ```purescript
> fib :: Int -> Int
> fib 0 = 1
> fib 1 = 1
> fib n = fib (n - 1) + fib (n - 2)
> ```

I don't know how to describe this "function definition syntax". From my experience, if I define a function multiple times, errors will occur, or the last definition would override previous definitions.

So I search with these keywords "haskell function definition", found those materials:

> We are not restricted to having single line definitions for functions. We can use multiple definitions combined with implicit pattern matching.
> -- https://www.cmi.ac.in/~madhavan/courses/pl2009/lecturenotes/lecture-notes/node70.html
>
> Pattern Matching
> ...
> -- https://www.tutorialspoint.com/haskell/haskell_functions.htm

Then I noticed this sentence form Chapter 4 mentioned pattern matching:

> when we cover _pattern matching_ later in the book

I think "pattern matching" should be at least briefly introduced before showing those examples. Because people like me never seen it 🤔

**Comment by razcore-art** [comment]
I'm going over the book once again and so I can leave some comments since it's all fresh.

I think pattern matching doesn't have to be introduced here, it's enough to make the connection with how case-based math functions are defined, eg.:

![](http://ximalas.info/wp-content/uploads/2013/12/funksjoner-med-cases-400x438.png)

If I'm not mistaking these functions are translated to actual case statements anyway so another way to go would be to introduce `case` syntax:

```ps
fact :: Int -> Int
fact n = case n of
  0 -> 1
  _ -> n * fact (n - 1)
```

**Comment by milesfrain** [comment]
I don't think it hurts to include more ways for readers to connect with the material (such as piecewise functions). Just need to make sure to emphasize that understanding this mathematical notation is not a prerequisite for learning PS.

[`case` syntax](https://book.purescript.org/chapter5.html#case-expressions) is also introduced in that next pattern matching chapter (ch5) so I don't know if that will help us in ch4, unless we reorder some material.

I'm also wondering what is the least confusing way to present the first `case` example:

```purs
-- underscore wildcard might be confusing
fact :: Int -> Int
fact n = case n of
  0 -> 1
  _ -> n * fact (n - 1)
```

```purs
-- I think this is clearest with separate (although redundant) x and n
fact :: Int -> Int
fact x = case x of
  0 -> 1
  n -> n * fact (n - 1)
```

```purs
-- The cleanest version (in my opinion), but point-free adds another layer of confusion
fact :: Int -> Int
fact = case _ of
  0 -> 1
  n -> n * fact (n - 1)
```

Ideally, I'd like to link to more of the [language reference](https://github.com/purescript/documentation/blob/master/language/Pattern-Matching.md) from the book to deduplicate some explanations and give us more flexibility in how we sequence content. Definitely some downsides with that proposal to watch out for.

**Comment by shaunplee** [comment]
Would it be reasonable to present these functions in Chapter 4 using only (mostly?) the syntax that has been introduced so far?

```
fact :: Int -> Int
fact n = if n == 0 then
          1
         else
           n * fact (n - 1)
```
and
```
fib :: Int -> Int
fib n = if n == 0 || n == 1 then
          1
        else
          fib (n - 1) + fib (n - 2)
```

**Comment by milesfrain** [comment]
That's another good suggestion. `if`/`else` should be very familiar for folks coming from many other language backgrounds.

I have no objections to including any or all of these additional presentations:
- Mathematical notation / piecewise functions
- Case expression (maybe as a preview for later chapters)
- `if` / `else`

We should be sure to emphasize that those other explanations are supplemental, so folks can skip over those if pattern matching clicked for them right away, since that's the most idomatic.

**Comment by Zelenya** [comment]
Seems to be addressed by https://github.com/purescript-contrib/purescript-book/pull/272
