### ISSUE TITLE
Ch4 'whereIs' function signature

### ISSUE THREAD

**Issue by mstream** [purescript-contrib/purescript-book#216]
https://github.com/purescript-contrib/purescript-book/blob/8e55a3cd6c2a73721709e23edd0e627590096c38/exercises/chapter4/test/Main.purs#L162-L168

The expected signature of the **whereIs** is `String -> Maybe String` which suggests that to solve this problem one has to import the example file tree (**root**) from the **Data.Path** module. That prevents the implementation to be reused outside of the context of that data set. In my opinion the **root** path should be passed as an argument like in other filesystem related exercises which would make its signature `String -> Path -> Maybe String`.

**Comment by milesfrain** [comment]
That sounds like a good change. Would you like to implement it? Wondering swapping the first two args would be better `whereIs :: Path -> String -> Maybe String`.

I also discovered that the [existing exercise example](https://book.purescript.org/chapter4.html#exercises-4) is incorrect. It should have been `whereIs "ls"` instead of `whereis "/bin/ls"`, but would be happy to see it change to `whereIs root "ls"`.
