### ISSUE TITLE
Ch4 largestSmallest test/solution uses Tuple

### ISSUE THREAD

**Issue by ericArbour** [purescript-contrib/purescript-book#221]
Hi there, I've been making my way through this book and loving the content and exercises so far. 

I wanted to share a small hiccup I ran into with the `largestSmallest` exercise in chapter 4. The test requires that the solution has a return type of `Array (Tuple String Int)`, however tuples have not yet been introduced to the reader and the exercise specifically asks to return "an array containing the single largest and single smallest files in the filesystem." 

It's a small inconsistency but either of these could make things a little clearer:
1) The exercise is explicit about using tuples.
2) The test/solution are updated to use `Array Path` instead.

I'm happy to submit changes if either of these are welcome updates. Thanks!

**Comment by mstream** [comment]
Having stayed with tuples, do you think that using `Tuple` instead of `Array` for the result type would be more apt? We are looking strictly for a pair and that could be expressed using the type system.

**Comment by ericArbour** [comment]
That sounds good to me, but I think the exercise instructions should mention `Tuple` so the reader has a bit of direction, since they haven't been introduced yet.

Looking at the current solution, it looks like `Tuple` was introduced as a replacement for the `File` constructor. I'm guessing this is because the `Path` constructors aren't exported from `Data.Path`. 

For reference:
```
maxSigned32BitInt :: Int
maxSigned32BitInt = 2147483647

largestSmallest :: Path -> Array (Tuple String Int)
largestSmallest path = largestSmallestPaths (allFiles path)
  where
  largestSmallestPaths :: Array Path -> Array (Tuple String Int)
  largestSmallestPaths paths = [ outlier (\i j -> i > j) 0 paths, outlier (\i j -> i < j) maxSigned32BitInt paths ]
    where
    outlier :: (Int -> Int -> Boolean) -> Int -> Array Path -> Tuple String Int
    outlier criteria startValue paths' =
      foldl
        ( \acc p' ->
            ( case size p' of
                Just n -> if criteria n $ snd acc then Tuple (filename p') n else acc
                Nothing -> acc
            )
        )
        (Tuple "" startValue)
        paths'
``` 

What do you think about exporting the `Path` constructors from `Data.Path` to allow the return type of `Tuple Path Path` instead of `Tuple (Tuple String Int) (Tuple String Int)` for this solution? I just learned `Data.Array` doesn't have a `foldl1` 🙁.

**Comment by milesfrain** [comment]
Another good catch.

This should return `Array Path` because then we can gracefully handle the corner cases of when there are zero or one file in the location to search (by returning an empty array or one-element array). I think this whole solution should be a rewrite, especially to get rid of `maxSigned32BitInt`. Also, the test should be flexible enough to allow any ordering of the returned array.

Note that many of these solutions and tests are crowd-sourced by fellow beginners, so there's plenty of opportunity to improve them. Wondering if that disclaimer should be added to the text.
In this case, the existing test/solution is incorrect. But you'll likely come across other situations where you come up with a cleaner solution than what's provided, so please share those in a PR. Same goes for improving exercise wording and tests.

Links for reference:
https://book.purescript.org/chapter4.html#exercises-4

https://github.com/purescript-contrib/purescript-book/blob/259fa0db61e6d11d9b30227bbdbf24f42f04c94b/exercises/chapter4/test/no-peeking/Solutions.purs#L100-L119

https://github.com/purescript-contrib/purescript-book/blob/259fa0db61e6d11d9b30227bbdbf24f42f04c94b/exercises/chapter4/test/Main.purs#L158-L161

**Comment by ericArbour** [comment]
Just put up a PR for this (#225). I'm happy to refine further if needed, thanks!
