### ISSUE TITLE
Rethink chapter dependencies

### ISSUE THREAD

**Issue by razcore-art** [purescript-contrib/purescript-book#245]
Some chapters depend on code from another chapter, see for example the chapters dealing with the address book (ch7, ch8, ch10).

We should have only one source of truth if possible. So I'm thinking we can do a script where we define dependencies and when we change one chapter the others get updated as well.

If there's some code that is designed specifically for a given chapter, like ch10 which includes generics, we could just add comments for that in the source code.

```purs
-- | Ignore these lines until ch10
```

Or something of that sorts.

We can probably use git hooks to auto-update dependencies after committing changes to a chapters. Say our dependencies are `[ch7, ch8, ch10]` and we work on ch8. The hooks will then just copy the dependencies to the other chapters once we're done and committed changes to ch8.

**Comment by milesfrain** [comment]
I agree that this code duplication is not ideal.

But we need to be careful that doing something too fancy in CI could make maintenance even more difficult or confusing. There's also some tricky corner cases.

> We can probably use git hooks to auto-update dependencies after committing changes to a chapters. Say our dependencies are `[ch7, ch8, ch10]` and we work on ch8. The hooks will then just copy the dependencies to the other chapters once we're done and committed changes to ch8.

With the above proposal, what do we do if:
* A commit updates more than one chapter? Fail CI?
* If content is removed in later chapters (rather than only being added). For example, we show both the `ado` and `<$>`-`<*>` / `map`-`apply` techniques in ch7, but get rid of that duplication in later chapters.

If we can find a good technique for tracking an evolving project, then that would have many applications beyond this book, such as what's discussed in https://discourse.purescript.org/t/svelte-hype-purescript-perspective/1851/3 .

We're currently just using this "folders" strategy:
> One of these approaches is in Make the Leap from JavaScript to PureScript breaking it down by folders instead of branches/tags.

Your original "track as tags" proposal in that thread lets git handle the above corner cases, and we could have a script expand each tag into a separate chapter folder (for reader convenience and mdbook code anchor compatibility), although that seems overkill with this book that doesn't really follow the intro's promise of building up a single app chapter-by-chapter. It would be a better fit for realworld halogen though. Another major challenge is that we'd be constantly rewriting history, and we'd definitely want to track these rewrites. For tracking an evolving sequence of commits, we'd probably need to use something like [git-series](https://github.com/git-series/git-series).

I'm thinking we should hold off on implementing this proposal for this book until it becomes a more obvious problem. So far, this hasn't been too painful. I've only had to update these three chapters in tandem once before.

**Comment by razcore-art** [comment]
I see, if the book doesn't have too much duplication problems apart from these chapters than yea, I'd say this isn't that bad. We don't need anything fancy.

Speaking of fancy, I would like the bare minimal implementation that works and doesn't create additional problems :). So I'll just finish up with a thought i had about this. I thought of using [git-hooks](https://githooks.com) so that on every commit we run a script that checks dependencies and just updates with the latest files (say based on time stamp). That's it.

So a concrete example we'd have something like `dependencies = [ [ ch7, ch8, ch10 ], [ch3, ch11], etc ]` and possibly more specific file dependencies. And that's it, then a script run on each commit via hooks and copies over the newest files avilable changes.

> If content is removed in later chapters [...]

I'm not sure I understand this part, I don't see any reason to not have the same source files, we just comment properly the parts in question, like

```purs
-- | This part is for ch7 strictly
code
-- | End for ch7
```

In any case, I'm closing this as it doesn't seem that relevant just yet.
