### ISSUE TITLE
Chapter 5 - Clipped exercise breaks Solutions.purs

### ISSUE THREAD

**Issue by shaunplee** [purescript-contrib/purescript-book#274]
Extending the `Shape` type to add a `Clipped` data constructor breaks the implementations in `Solutions.purs` such that the tests will no longer run.

If readers are not supposed to be peeking at the solutions anyway, maybe adding a Partial constraint to the solutions (as suggested by the compiler) would be an easy-ish way to keep things moving for the reader.

**Comment by milesfrain** [comment]
Nice find.

> If readers are not supposed to be peeking at the solutions

Readers can look at those for comparing against their own solutions. Just wanted to discourage folks from giving-up too soon. So ideally, we'd keep those as similar as possible (e.g. no Partial if we can avoid it).

I think this would also be fixed by having the [resetSolutions.sh](https://github.com/purescript-contrib/purescript-book/blob/671243109bae2a10d5571d92058d75b11ac99873/scripts/resetSolutions.sh) script move `no-peeking` up a level outside of the compilation path. I'm working on a PR that explores this option.
