### ISSUE TITLE
Chapter 3: Infix function application example using record accessors does not seem to work

### ISSUE THREAD

**Issue by shaunplee** [purescript-contrib/purescript-book#282]
Chapter 3 includes the following as an example of how `($)` can make things easier to read by reducing the number of parentheses:

> For example, the following nested function application, which finds the street in the address of an employee's boss:
> ```haskell
> street (address (boss employee))
> ```
> becomes (arguably) easier to read when expressed using $:
> ```haskell
> street $ address $ boss employee
> ```
However, these `street`, `address`, and `boss` accessor functions are not defined. I think this would be valid Haskell when using record syntax, but, based on my quick experiments in PSCi 0.13.8, it seems like PureScript doesn't automatically create these accessor functions.

I'm new to PureScript, so I could be missing something here.

Suggestion is to rewrite this a bit, maybe by introducing record accessor functions using `_.` per issue #281, and then rewriting the above as:
> For example, the following nested function application, which finds the street in the address of an employee's boss:
> ```haskell
> _.street (_.address (_.boss employee))
> ```
> becomes (arguably) easier to read when expressed using $:
> ```haskell
> _.street $ _.address $ _.boss employee
> ```

I can take a crack at this, unless I'm misunderstanding how PureScript works.

**Comment by milesfrain** [comment]
Yeah, this is a very hand-wavy snippet. I think we could completely eliminate that section and in the preceding section just link to the docs for [`$`](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Data.Function#v:($)). We can improve those docs if they're not beginner-friendly enough.

For context, a lot of the book's address records were [previously wrapped in `Newtype`](https://github.com/purescript-contrib/purescript-book/issues/118) to work around some of the limitations of records, and it was common to have helper functions to unwrap the fields (since I don't think `wrap`/`unwrap` were available for `Newtype` yet either). Anyway, things are a lot easier now. In the real world, assuming we had a `boss :: Entry -> Entry` function, that snippet would just be written as:
```purs
(boss employee).address.street
```
