### ISSUE TITLE
Ch13 - clarify exercise to "simplify the result of 'quickCheckPure'"

### ISSUE THREAD

**Issue by shaunplee** [purescript-contrib/purescript-book#306]
Chapter 13 has the following exercise, which was added in commit 46d5d2bfe926b0656118963e120f61ee8f076b4d:

> 4. (Medium) Use the `all` function to simplify the result of the `quickCheckPure` function - your function should return `true` if every test passes, and `false` otherwise. Try using the `First` monoid, defined in `monoids` with the `foldMap` function to preserve the first error in case of failure.

I am having trouble understanding this exercise. The first sentence makes it sound like the exercise is to write a function of type `List Result -> Boolean` using the `all` function.

However, it is unclear how to make this work with the second sentence, which asks that we try to "preserve the first error in case of failure" because I don't see how I can encode the first error in a `Boolean`.

Is the exercise asking the reader to write two functions, one with type `List Result -> Boolean` and another with type `List Result -> First String`?

Also, I can't seem to find a `monoids` package that includes a `First` newtype. (There seems to have been a `monoid` package that is now deprecated due to being merged into `prelude`.) Searching pursuit for "First," it seems like the `First` newtype from `Data.Maybe.First` is the monoid most similar to the one called for. If that's the case, then I can update the text to match.

**Comment by milesfrain** [comment]
All good points.

I went into skim mode by the end of Ch13, so didn't get around to attempting that exercise, but I think a `squashResults :: List Result -> Result` is in the spirit of what it wants readers to do.

Doesn't look like `foldMap` will work, since there's no `mempty`/`Monoid` for `Result`.
I don't see how `Data.Semigroup.First` will play a part in the solution.
You could use `Data.Maybe.First`. There might be some even nicer ways to tackle this.

Also, it would be great if we could setup some exercise framework for this chapter. I was kinda stumped on what to do with this, since it's inverted where we're finally asking the readers to write the tests.

**Comment by milesfrain** [comment]
Also interesting that `all`-support for `Result` was proposed at one point, but doesn't follow the laws. https://github.com/purescript/purescript-quickcheck/pull/101

**Comment by hdgarrood** [comment]
The `Semigroup` and `Monoid` instances there are fine, it was just the `HeytingAlgebra` instance which was problematic.
