### ISSUE TITLE
Chapter4: Wrong Fibonacci function definition?

### ISSUE THREAD

**Issue by sunakane** [purescript-contrib/purescript-book#315]
In chapter4, the implementation of Fibonacci function is as follows:
```
fib :: Int -> Int
fib n =
  if n == 0 || n == 1 then
    1
  else
    fib (n - 1) + fib (n - 2)
```

However, Fibonacci function is supposed to return 0 when the argument is 0.
https://en.wikipedia.org/wiki/Fibonacci_number

Is this a mistake?

**Comment by hdgarrood** [comment]
It’s not a mistake; it’s actually not wrong. I would argue that the Wikipedia page is wrong for suggesting that there is just one “correct” definition, because in practice there isn’t. In Fibonacci’s original definition of the function it was to describe the growth of a rabbit population after a given number of months:

> Fibonacci considers the growth of an idealized (biologically unrealistic) rabbit population, assuming that: a newly born breeding pair of rabbits are put in a field; each breeding pair mates at the age of one month, and at the end of their second month they always produce another pair of rabbits; and rabbits never die, but continue breeding forever.

In this setting you have to start from 1, not 0 - you can’t breed any rabbits if you start with 0 pairs of rabbits.
