### ISSUE TITLE
Version the book according to PureScript version

### ISSUE THREAD

**Issue by FranklinChen** [purescript-contrib/purescript-book#35]
As PureScript evolves, it may be useful to have tagged versions of this book corresponding to PureScript version.

**Comment by swuecho** [comment]
seems  psc version matters too. 

 "set": "psc-0.13.2" will not work if psc-package version is 0.13.4

(In my first 30mins trying Purescript)

**Comment by dwhitney** [comment]
I don't think I've got enough time to keep tagged versions of the book, but we are upgrading to spago, which I think offers a solution to this problem. I'll have to think about it. Either way thanks for the feedback and thank you for highlighting this.

**Comment by swuecho** [comment]
Yes. I just figure out that using `spago init` in the execise folder is enough

**Comment by milesfrain** [comment]
Version info can be found in any of the `exercises/chapter*/packages.dhall` files.
For example:
```dhall
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.13.6-20200507/packages.dhall
```
Corresponds to compiler version `0.13.6`.

These files should all be identical, since they are copied from [`scripts/packages.dhall`](
https://github.com/purescript-contrib/purescript-book/blob/master/scripts/packages.dhall) whenever we bump the package set.

Tagging the repo may also be useful, but that's one more thing to worry about becoming out of sync. I'd welcome any PRs to automatically apply these tags based on `packages.dhall` contents during CI.
