### ISSUE TITLE
chapter 5: `sameCity` is not compiling with partial type pattern matching

### ISSUE THREAD

**Issue by aonemd** [purescript-contrib/purescript-book#368]
This solution, given under no-peeking section, does not compile:

```purs
type Address = { street :: String, city :: String }
type Person = { name :: String, address :: Address }

sameCity :: Person -> Person -> Boolean
sameCity { address: { city: c1 } } { address: { city: c2 } }
  | c1 == c2 = true
  | otherwise = false
```

As far as I know, the type Person must be passed fully? so no partial row here. Is that correct? Is there's something I'm missing here?

**Comment by gomain** [comment]
I don't recall running into this. @aonemd can you provide the full error?

**Comment by aonemd** [comment]
Sorry. That was a false alarm from a beginner. Nothing is wrong here. My mistake. I forgot to cover all cases with guards.

**Comment by JohnGurin** [comment]
What's the point of `otherwise` branch?
```purescript
sameCity { address: { city: c1 } } { address: { city: c2 } } = c1 == c2
```

**Comment by JordanMartinez** [comment]
```
type Address = { street :: String, city :: String }
type Person = { name :: String, address :: Address }

sameCity :: Person -> Person -> Boolean
sameCity { address: { city: c1 } } { address: { city: c2 } }
  | c1 == c2 = true
  | otherwise = false
```
`otherwise` is an alias for `true`. So, if `c1 == c2` is false, then the expression for that pattern, `true`, won't be returned. Instead, the code will look at the next pattern guard, `otherwise`. Since that's always true, the compiler can verify that this function is total. In this case, the concern of totality is whether the function always returns something of type Boolean. If `otherwise` and its corresponding expression was dropped, the function would return `undefined` in one case and `true` in another. In PS, `undefined` is not a value of type `Boolean`.

**Comment by JohnGurin** [comment]
Sorry, if it was implied somehow and I did not get it. Why `c1 == c2` is not enough? Isn't `(==)` total by itself?

**Comment by JordanMartinez** [comment]
`c1 == c2` is enough. I also don't know why it's written like this.
