### ISSUE TITLE
Ch. 2 last exercise on spago installing purescript-globals behaves unexpectedly

### ISSUE THREAD

**Issue by oldfartdeveloper** [purescript-contrib/purescript-book#61]
Towards the end of the 2nd chapter is the **last exercise** which is as follows:

---

2. (Medium) Use `spago install` to install the `purescript-globals` package as a dependency. Test out its functions in PSCi (_Hint_: you can use the `:browse` command in PSCi to browse the contents of a module).

---

When I do `spago install purescript-globals`, it yields the following:

```zsh
[warn] The package 'purescript-globals' was not found in your package set, but 'globals' was. Using that instead.
[warn] Configuration file was not updated.
[info] Installation complete.
```

This sent me down a rabbit hole where I realized that `bower install purescript-globals` might have been used originally.

In any case, the existing behavior is sufficiently different to be confusing to at least this reader:

1.  `globals` is already available at this Purescript version level.
1.  But it's imported as `Globals`.

So I don't know what's expected in this exercise; much of the "connecting information" is missing.

Would the following work better?

---

2. (Medium) Use `spago ls packages` to show where packages are stored in **GitHub** and what their global names are:
    1.  In this command's response, locate the `purescript-globals` entry and browse its **[GitHub](https://github.com/purescript/purescript-globals)** entry.
    1.  Browse its **[Documentation](https://github.com/purescript/purescript-globals#documentation)** link and click the **[link](http://pursuit.purescript.org/packages/purescript-globals)** in its text.
    1.  Observe what **module** names are implemented in this GitHub project.
    1.  Test out its functions in PSCi (_Hint_: you can use the `:browse` command in PSCi to browse the contents of a module).

---

I'll be glad to do whatever the group decides as a PR.

**Comment by milesfrain** [comment]
Sorry for taking so long to review this issue. I just subscribed to notifications for this repo, so hopefully I'll have faster response time to new issues and PRs.

Thanks for taking a thorough look at all the exercises and helping to make this guide smoother for future readers.

It looks like there's a few confusing things going on:

1. Spago is more flexible than bower and the `purescript-` prefix is optional. So either `globals` or `purescript-globals` will work. The "[warn]" could be misleading though, and this should probably be mentioned somewhere.

2. It looks like the skipped installation in your log snippet is because the package was installed earlier:
```
miles@x1c5 ~/t/t/p/e/chapter2> spago install purescript-globals
[warn] The package 'purescript-globals' was not found in your package set, but 'globals' was. Using that instead.
[info] Installing 6 dependencies.
[info] Searching for packages cache metadata..
[info] Recent packages cache metadata found, using it..
[info] Copying from global cache: "maybe"
[info] Copying from global cache: "newtype"
[info] Copying from global cache: "invariant"
[info] Copying from global cache: "functions"
[info] Copying from global cache: "control"
[info] Copying from global cache: "globals"
[info] Installation complete.

miles@x1c5 ~/t/t/p/e/chapter2> spago install purescript-globals
[warn] The package 'purescript-globals' was not found in your package set, but 'globals' was. Using that instead.
[warn] Configuration file was not updated.
[info] Installation complete.
```

I don't think we should ask users to run `spago ls packages`.

Maybe this should be the extended exercise:

2. (Medium) Use spago install to install the `purescript-globals` package as a dependency. Test out its functions in PSCi (Hint: Search for the package on pursuit to find the necessary module names to import. The module contents are both listed on pursuit and with the `:browse` command in PSCi after importing the module).

Also, the [Tracking Dependencies](https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter2.md#tracking-dependencies) section should probably be updated to mention the following:
* The `purescript-` prefix is optional, so `spago install math` and `spago install purescript-math` are equivalent.
* The installed package will also be listed in `spago.dhall`

Feel free to apply any of the above suggestions (with or without modifications) in a PR and I'll review. We'll have to wait for someone else to merge the changes though.

**Comment by JamieBallingall** [comment]
I think the Tracking Dependencies section should be updated with the bulk of the required information so that the question can be as simple as possible.
Specifically, the section needs to mention:
* The `purescript-` prefix is optional
* The prefixless syntax is preferred since it does not generate a warning
* The installed package will also be listed in spago.dhall
* The module name required for import may not be the same as the package name
* Pursuit is the right place to look for the module names and functions

Then the hint might be "(Hint: In addition to Pursuit, the `:browse` command in PSCi can be used to discover the contents of a module"). Or, it could be dropped altogether. I think keeping the text of the exercises short helps them feel less intimidating.

**Comment by milesfrain** [comment]
@JamieBallingall I agree with your suggestions. And I have no strong feelings about whether or not to include `:browse`. I don't use PSCi much at all for development, and tend to just browse pursuit.

**Comment by oldfartdeveloper** [comment]
@milesfrain and @JamieBallingall: thanks for your input.

Chapter 2 is where the reader first seriously starts to learn Purescript; I believe the chapter is by its very location and scope is going to be overwhelming to many readers.  This is not a criticism; any project's "chapter 2" will be similarly challenging.

Hence, I agree that it's a good idea to keep the material as simple as possible.

Since I haven't gone through the entire book yet, I don't know when the details of these operations are described in a "training format"; I'll keep an eye out as I go along.

Here are my thoughts on modifying the exercise:

1.  There is no need to mention the detail that you don't need to include the `purescript-` prefix.  In this exercise, simply specify `globals`.
1.  I'm torn on whether to show `:browse` or simply reference the reader to **pursuit**.  On the one hand, **pursuit** is important to learn to navigate because it frequently has useful information above and beyond the signatures, but `:browse` is convenient to show the signatures; indeed I found I can use `:browse` more reliably than `:type`.  I finally fall on the side of mentioning both because:
    * `:browse` is a reliable quick lookup.
    *  **pursuit** has additional information which I've frequently found to be very helpful.

Hence: see what you think on the changes in the **PR #65**.

**Comment by milesfrain** [comment]
I agree about the overwhelming material, and think it's tougher in PS versus other languages. I suspect there's some survivorship bias where we don't hear much from the folks who read a chapter or two, find it too unapproachable, and then silently move-on to something else. So definitely bring-up anything that could be improved in the book.

Filed #66 to propose removing all of the `purescript-` prefixes in all chapters. For example "the `purescript-math` package" should just be referred to as "the `math` package".

> I don't know when the details of these operations are described in a "training format"

Which operations? Spago commands, or PSCi?

**Comment by milesfrain** [comment]
Closing this now that #65 is merged.
A remaining todo is tracked in #66.
If there's anything else I missed in here, feel free to comment/reopen, or file another issue.
