### ISSUE TITLE
ch4 - add tests

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#99]
Assigned to @oldfartdeveloper

Parent task #79

**Comment by oldfartdeveloper** [comment]
@milesfrain Thanks!

**Comment by oldfartdeveloper** [comment]
@milesfrain 

I'm ready to submit a PR, but I'm not sure of what we're adding here.  From your Chapter 6 PR, I see you want to merge your branch `ch6-tests` to `master`.

So what does that leave for the content in your branch `ch6-solutions`?  Are those to be merged into a different branch in `purescript-contrib/purescript-book` (say `ch6-solutions)?

I think it's a good idea to include solutions; just wondering what your intentions are?

**Comment by milesfrain** [comment]
> Are those to be merged into a different branch in `purescript-contrib/purescript-book` (say `ch6-solutions)?
Yep. The plan is to merge those into the "solutions" branch (solutions for all chapters will go here). I'll get that setup soon.
In the meantime. Feel free to submit your tests PR.

**Comment by milesfrain** [comment]
Make your ch4-tests PR to the master branch and your ch4-solutions PR to the solutions branch.
Examples of PRs to the solutions branch are #101 and #102.
These should have all tests "unlocked" by removing the block comments from `test/Main.purs` so we can eventually use this branch as part of CI testing.

**Comment by oldfartdeveloper** [comment]
Yep, I get it.  Thanks

**Comment by oldfartdeveloper** [comment]
There is an exercise in Ch 4 to find the *cartesian product* of two arrays.  When I look up the definition, the 2 arrays are commonly applied to apply to different types.  For example. Wikipedia shows this ![example](https://upload.wikimedia.org/wikipedia/commons/4/4e/Cartesian_Product_qtl1.svg).
See how one array is integers and the other is strings?

Now, the book hasn't defined `Tuple` yet, which would be the ideal item to use in the results array.l  So we have choices:

1.  Briefly introduce the `Tuple` to emphasize that the result array has different types in each element.
1.  Use `Array` containing two elements that have to be the same type.  Personally, I believe this is misleading and therefore confusing.
1.  Use `Record` consisting of fields `fst` and `snd` so that they will recognize the `Tuple` in subsequent exercises.  Unfortunately, `record` isn't introduced thus far in book either.

I recommend the `Tuple` but we'll have to enhance the text in the book a bit.

What do you think?

**Comment by oldfartdeveloper** [comment]
@milesfrain Another problem with the `cartesian product` exercise.  If you pass either parameter as an empty array, the code won't compile.  One possibility is to note this in the problem statement, and indicate that using `NonEmpty` instead of `Array` solves this problem.

I'm glad to attempt to update the text a bit to make this point.

Thoughts?

**Comment by milesfrain** [comment]
To be really strict (according to wikipedia) the Cartesian product inputs should be sets. But I think it's fine for the inputs to be arrays, and also common for the outputs to be arrays of two elements too.

Also, I think you can fix your compilation error with a type annotation. For example, change the input from:
```[]```
to
```([] :: Array Int)```
and I think it will work.

**Comment by oldfartdeveloper** [comment]
@milesfrain this worked:

```haskell
        test "Left array is empty"
          $ Assert.equal ([] :: Array (Array String))
          $ cartesianProduct [] ["five"]
        test "Right array is empty"
          $ Assert.equal ([] :: Array (Array String))
          $ cartesianProduct ["5"] []
```

which makes sense.  Thanks for your suggestion.

**Comment by oldfartdeveloper** [comment]
@milesfrain PRs #104 and #106 are submitted and ready to check

**Comment by milesfrain** [comment]
Closing now that #106 and #107 are merged
